### ISSUE TITLE
advice on how to set up clj-async-profiler as an on-demand profiler

### ISSUE THREAD

**Issue by barkanido** [clojure-goes-fast/clj-async-profiler#12]
hey, can you explain how to set up clj-async-profiler to profile an external process in production?

Is this library meant to be used as a dependency for a running process and can be accessed a web interface? or can it be run as a sidecar and profile another pid?

**Comment by alexander-yakushev** [comment]
Hi, you can absolutely add it as a dependency and launch within your application process. `serve-files` function sets up some basic web interface, but if you need more, you can always use `start` and `stop` functions for fine-grained control over what and how you are profiling.

It can be run as a sidecar process as well, however that is usually less convenient.

**Comment by barkanido** [comment]
I see. I will test this usage. thanks!
