### ISSUE TITLE
clj-async-profiler on WSL in `:itimer` doesn't generate data

### ISSUE THREAD

**Issue by genmeblog** [clojure-goes-fast/clj-async-profiler#13]
I'm trying to use clj-async-profiler on WSL.

WSL is not supported when `:cpu` profiling is set but async-profiler authors recommend using `:itimer` instead. But `:itimer` unfortunatelly doesn't generate any data (files are empty) with error:

```
Execution error (ExceptionInfo) at clj-async-profiler.core/run-flamegraph-script (core.clj:142).
ERROR: No stack counts found
```

`:alloc` profiling works.

I'm not sure if it's related to `clj-async-profiler` or maybe `async-profiler` itself (I don't know how to check it).

More details:

- WSL 1.0, with Linux kernel 4.4 (Ubuntu 18.04.3)
- OpenJDK 11.0.5
- Clojure 1.10.1
- Lein 2.9.1, run as `lein repl` (connection from Emacs/Cider)
- tested on supported `libasyncProfiler.so` and locally compiled
- tested with recommended JVM settings

**Comment by genmeblog** [comment]
Looks like `async-profiler` problem.

**Comment by alexander-yakushev** [comment]
Yeah, nothing we can do on our side, unfortunately.

**Comment by genmeblog** [comment]
`async-profile` author just committed quick fix to enable `:cpu` mode. See: https://github.com/jvm-profiling-tools/async-profiler/issues/286
I'll check later if it helps.

**Comment by genmeblog** [comment]
I can confirm, newest (compiled from source) `async-profile` solves problem and `:cpu` works now.

**Comment by alexander-yakushev** [comment]
Thanks for the heads up!
