### ISSUE TITLE
Regression from 0.4.0 -> 0.4.1

### ISSUE THREAD

**Issue by blueberry** [clojure-goes-fast/clj-async-profiler#16]
When running the hello world from the home page, I get a ClassCastException that LinuxVirtualMachine cannot be cast to VirtualMachine.

With 0.4.0 everything works as expected.

Is there any new requirement introduced in the meantime?

My specs: Arch Linux (latest), Open JDK 1.8.0_242. Using leiningen.

**Comment by alexander-yakushev** [comment]
Hi Dragan! Nothing has changed between 0.4.0 and 0.4.1 that could cause this; but people reported some problems with Leningen lately.

Could you paste the whole stacktrace please?

Also, do you confirm that on the exact same setup, 0.4.0 works but 0.4.1 does not?

**Comment by blueberry** [comment]
Hi Alex. I can confirm that everything worked with 0.4.0, but failed with 0.4.1. Returning back to 0.4.0 again worked.

However, when I updated Arch and rebooted, now 0.4.1 works, too. So, it seems that something on my system caused this.

Sorry for raising a false alarm!

**Comment by alexander-yakushev** [comment]
No problem. Feel free to reopen if you get the same error again :)
