### ISSUE TITLE
Setup documentation is a bit lacking

### ISSUE THREAD

**Issue by narkisr** [clojure-goes-fast/clj-async-profiler#2]
I had some issue with setting the project on my machine:

* The tools-jar-loaded function does not seem to work when running from lein, I had to use lein-jdk-tools plugin.

* I had to enable non root perf support:
```bash
  $ echo 0 > /proc/sys/kernel/kptr_restrict
  $ echo 1 > /proc/sys/kernel/perf_event_paranoid
```

**Comment by alexander-yakushev** [comment]
Sorry for the late answer, I somehow managed to miss your message. 

Indeed, it doesn't work for in Leiningen on Linux, but it works in Lein on Mac. It also works in Boot on both OSes.

Could you please test `0.1.3-SNAPSHOT`? I changed the way I load `tools.jar` and now it works for me on Lein+Linux too. Can you confirm?

**Comment by alexander-yakushev** [comment]
Fixed the Leiningen issue and added the necessary steps to the README. Thank you!
