### ISSUE TITLE
Support for OpenJDK?

### ISSUE THREAD

**Issue by hlship** [clojure-goes-fast/clj-async-profiler#21]
I'm attempting to use this with OpenJDK 8 and 16; in both cases, I get the following failure:

```
(prof/profile (test-benchmark :deep))
Execution error (ExceptionInfo) at clj-async-profiler.core/start (core.clj:264).
Could not find libjvm among loaded libraries. Unsupported JVM?
```

Are the underlying libraries dependent on Oracle JDK or should they work with OpenJDK and I'm just doing something wrong?

I'm on Mac OS X, and have installed OpenJDK using Homebrew.

**Comment by alexander-yakushev** [comment]
Hello! It certainly does work with OpenJDK, and should work with any compliant JDK distribution. What does `java -version` tell you?

Also, could you extract the complete stacktrace? Probably `(pst)` would do that.

**Comment by alexander-yakushev** [comment]
@hlship Hello Howard, did you ever get around this issue?

**Comment by hlship** [comment]
I'm sorry; memory fails, and since I've moved on from Walmart, and I don't have access to my old machine and notes.  I believe I did get it to work.

**Comment by alexander-yakushev** [comment]
No problem, thanks anyway!
