### ISSUE TITLE
Any possible support for metadata?

### ISSUE THREAD

**Issue by Folcon** [clojure-goes-fast/clj-async-profiler#22]
Hey, this is a great project thanks so much for making it =)...

I was just wondering if there's any way I could pass in a map of `:metadata` arguments to the profile which would then get written into the result? It would just make it much easier to pass in stuff like version numbers so when I'm looking back at historical profiles I can see for example what commit hash produced it, so when I'd doing comparisons I'm pretty sure what I'm looking at.

Does the underlying format have support for adding attributes like that? Or should I be looking to record this sort of stuff on my side? No problem if that's the case btw =)...

**Comment by alexander-yakushev** [comment]
Hello @Folcon! Would passing a custom `:title` string help? It will get written into the resulting HTML file, so that you can then distinguish the profiles by it.
