### ISSUE TITLE
Any plans to update java-async-profiler?

### ISSUE THREAD

**Issue by niquola** [clojure-goes-fast/clj-async-profiler#23]

**Comment by CRHough** [comment]
Assuming you want an updated libasyncProfiler there is an included facility already. [Go to async-profiler/releases](https://github.com/jvm-profiling-tools/async-profiler/releases) and download the desired "async-profiler-*" archive(s). Copy the "libasyncProfiler" shared library from the archive's build directory to your project's resources/libs directory and rename as appropriate (e.g., from "libasyncProfiler.so" to "libasyncProfiler-2.8-linux-x64.so").

After you have the updated lib(s) is just a matter of `reset!`ing the `async-profiler-agent-path` atom to "resources/libs/<whatever>".

Tested with OpenJDK 11 & 17 on Linux with libasyncProfiler 2.8 libs.
