### ISSUE TITLE
unable to run profiling due to invalid module access in java 17? 

### ISSUE THREAD

**Issue by jlb0170** [clojure-goes-fast/clj-async-profiler#24]
java.lang.reflect.InaccessibleObjectException: Unable to make field private final sun.management.VMManagement sun.management.RuntimeImpl.jvm accessible: module java.management does not "opens sun.management" to unnamed module @38dacb78

this is after adding "--add-opens=java.management/sun.management=ALL-UNNAMED" to the command line (via project.clj jvm-opts) and confirming that it is being added to the command line.

**Comment by jlb0170** [comment]
(This was working fine with Java 8 but we recently upgraded to 17 and the next time we ran, it was no longer working.

**Comment by jlb0170** [comment]
pebkac sorry

**Comment by alexander-yakushev** [comment]
What did the BKAC operator do, just for posterity? 😄

**Comment by jlb0170** [comment]
I had the add-open option set in the prod profile in lein, and i was running in the dev profile by default and didn't realize it at first. I'm still having a problem with stale classes in one process, but i got it working in a different class, so that still seems like a me problem.

**Comment by alexander-yakushev** [comment]
Wait, so you are saying that you need `-add-open` for clj-async-profiler to work on latest JDK? Because it shouldn't be needed.

**Comment by jlb0170** [comment]
i did, although it isn't the latest jvm, it was java 17. i guess it is the latest LTS version though, and yeah, I appeared to need it. The error above I was getting; it went away after correctly setting the add-open for java.management/sun.management in my lein profile.

**Comment by alexander-yakushev** [comment]
Weird, I have [tests](https://app.circleci.com/pipelines/github/clojure-goes-fast/clj-async-profiler/123/workflows/1dc18a4a-5791-49e6-9ecf-0b9306e67f96/jobs/680) running against JDK17 and they work without having add-open.

Would you care enough to make a small reproducible, please? Like a blank project that only depends on the profiler and throws InaccessibleObjectException on JDK17.

**Comment by jlb0170** [comment]
that is weird. I will attempt to find time to do this this week, although tbh since i got it working it's a little hard to justify the effort, so no promises - i closed the bug because i assumed it's a me problem, but I'll see what i can do in case it is a common problem.
