### ISSUE TITLE
Is it possible to generate a diffgraph from the UI and from different runs?

### ISSUE THREAD

**Issue by cleeland** [clojure-goes-fast/clj-async-profiler#35]
[The documentation for diffgraph](http://clojure-goes-fast.com/kb/profiling/clj-async-profiler/diffgraphs/) describes a means for generating a diffgraph using the repl and seemingly only between runs from the same process.  Is it possible to generate them somehow from the UI and across different runs?

I'm assuming that it's NOT possible as code is currently written, otherwise you'd describe it.  I think the question I'm really asking is whether there is something that fundamentally prevents such a diff, e.g., the data from two runs lacks sufficient context to properly diff them, or whether it's simply that nobody's done the plumbing to set it up yet.

**Comment by alexander-yakushev** [comment]
You can pass two txt files to generate-diffgraph. I'll take a look at the documentation once I'm near the keyboard.

**Comment by alexander-yakushev** [comment]
You can now create diffgraphs from the web UI in `1.4.0`, including between the profiles taken in different runs.
