### ISSUE TITLE
Locally saved flamegraph files don't work correctly

### ISSUE THREAD

**Issue by kenhuang-io** [clojure-goes-fast/clj-async-profiler#41]
Hi,

This is a fantastic tool and it's very easy to use and powerful, thanks!

I successfully profiled a function yesterday and it worked perfectly on the web UI. And then I saved the HTML file, in the hope that I can reuse it later. But the local HTML copy didn't work properly today, the flamegraph just didn't show up, is it possible to do that? Or is it just that something went wrong on my side?

Thanks!

**Comment by alexander-yakushev** [comment]
Hello! I'll check why a flamegraph saved from the browser doesn't work, honestly I've never tried that. All flamegraphs that you see on the web UI are stored in /tmp/clj-async-profiler/results/ directory, so you can take them from there. Or are you profiling a remote host and don't have an easy access to its local files?

**Comment by alexander-yakushev** [comment]
Another option to try would be not to save the page when the flamegraph is already open, but from the index page right click the flamegraph link and select Save page as... or whatever it's called.

**Comment by kenhuang-io** [comment]
> Hello! I'll check why a flamegraph saved from the browser doesn't work, honestly I've never tried that. All flamegraphs that you see on the web UI are stored in /tmp/clj-async-profiler/results/ directory, so you can take them from there. Or are you profiling a remote host and don't have an easy access to its local files?

It turns out that web browsers, both firefox and chrome in my case, have tempered the html file for saving, and it's not clj-async-profiler's problem at all.

Like you said, we can use "right click and save as" method or use `curl` to do the trick.

Thanks for your quick replies, and I'm closing this now.

**Comment by kenhuang-io** [comment]
> Another option to try would be not to save the page when the flamegraph is already open, but from the index page right click the flamegraph link and select Save page as... or whatever it's called.

Maybe we can make it more user-friendly by putting a "save as" or "download" button next to the link?

**Comment by alexander-yakushev** [comment]
I'll consider it, thank you!
