### ISSUE TITLE
Empty output, + ERROR: No stack counts found

### ISSUE THREAD

**Issue by blueberry** [clojure-goes-fast/clj-async-profiler#5]
Hi. Thank you for bringing attention to async-profiler, and for creating this package.

I've tried running an example you've provided on the homepage and the introductory blog post, and, while the package seems to work, the resulting /tmp/clj-async-profiler/... txt files are empty. The SVG file that prof/stop returns does not exist on disk.

The only complaint from (clj-)async-profiler is an error message printed in the repl (probably to err by the native binary itself) that says "ERROR: No stack counts found". 

My system is a recent Arch Linux, OpenJDK 8, clj-async-profiler 0.1.3.

Any hints?

**Comment by alexander-yakushev** [comment]
Hello Dragan, can you please tell which build tool/runner you are using (Lein, boot, clj) and which version of it?

**Comment by blueberry** [comment]
Leiningen 2.8.1 on Java 1.8.0_162 OpenJDK 64-Bit Server VM

**Comment by alexander-yakushev** [comment]
I've just double-checked, it works for me on Ubuntu and Lein 2.8.1.

I assume you are running an x86_64 system?

**Comment by blueberry** [comment]
Yes. 

A couple of things that I'm not completely sure about:
1. Is there anything additional to adding clj-async-profiler to the leiningen project that I should do?
2. How do I check if I have debug symbols enabled for the JVM? Could this be the source of the problem?

**Comment by alexander-yakushev** [comment]
Debug symbols shouldn't cause a problem here. And there is no additional config, really.

Let's do it once more step by step.

1. `lein new ap-test`.
2. Edit `project.clj`, add `[com.clojure-goes-fast/clj-async-profiler "0.1.3"]` to dependencies.
3. `lein repl`
4. `(require '[clj-async-profiler.core :as p])`
5. `(p/profile-for 10 {})`
6. After 10 seconds, two files should be present in `/tmp/clj-async-profiler/results/`.

`ERROR: No stack counts found` is reported by flamegraph generation script when it sees an empty file. Is that message shown again?

**Comment by blueberry** [comment]
I assume step 3 is `lein repl` instead of `lein run`. When I do this in vanilla terminal, I get a dozen of: 

```
perf_event_open failed: Permission denied
```

printouts rigth after step 5.

The txt files in results are empty. No svg files are there.

**Comment by alexander-yakushev** [comment]
Are you doing this inside a Docker container, by chance?

**Comment by blueberry** [comment]
No. I'm doing it in vanilla desktop arch linux with x server and x monad, without Gnome or KDE or anything, with a normal account that has no exotic restrictions. All usual C development tools are recent, and I do lots of development on this machine...

**Comment by alexander-yakushev** [comment]
By Googling this message I found that newer Linux kernels have `perf_event_paranoid` set to 2 instead of 1, which restricts doing any kernel profiling from userspace.

Please, try doing `echo 1 | sudo tee /proc/sys/kernel/perf_event_paranoid` and try the profiler again.

**Comment by blueberry** [comment]
That didn't help.

Interestingly, running it as `sudo lein repl` works!

**Comment by alexander-yakushev** [comment]
Has the `/proc/sys/kernel/perf_event_paranoid` file changed? Does `cat /proc/sys/kernel/perf_event_paranoid` prints 1?

Can you also try setting it to 0?

**Comment by blueberry** [comment]
No, it prints 2. It seems that it's not being set by the command you suggested.

**Comment by alexander-yakushev** [comment]
I made a mistake initially:

`echo 1 | sudo tee /proc/sys/kernel/perf_event_paranoid`

**Comment by blueberry** [comment]
Works like a charm now! Many thanks!

**Comment by alexander-yakushev** [comment]
Thank you for reporting! I'll update the README now.

**Comment by alexander-yakushev** [comment]
Meh, I should've read async-profiler updates 😄 https://github.com/jvm-profiling-tools/async-profiler#basic-usage

**Comment by blueberry** [comment]
They seem to have the same > mistake in their README :) Or not. Now I see that they echo directly, not via `tee`.

**Comment by alexander-yakushev** [comment]
It's not a mistake in their case since they are echoing directly into a file. But you must be a root user to do that. You can't do `sudo echo 1 > somefile` because it will only run `echo` from root but not the redirection itself. So another way is to do `echo 1 | sudo tee somefile`. Tee can be described as "output redirection as a program".
